name: brick_breaker_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  widget_and_text_animator: ^1.1.5
  avatar_glow:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: "^0.13.1"
  
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.jpg"

flutter:
  uses-material-design: true
  fonts:
    - family: CabinSketch
      fonts:
        - asset: fonts/CabinSketch-Regular.ttf
        - asset: fonts/CabinSketch-Bold.ttf
  assets:
    - assets/logo.png